In [3]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(repr(arr))

array([1, 2, 3, 4, 5])


In [9]:
import numpy as np
arr = np.array([23.34, 1, 2, 3, 4, 5])
print(repr(arr))

array([23.34,  1.  ,  2.  ,  3.  ,  4.  ,  5.  ])


When the elements of a NumPy array are mixed types, then the array's type will be upcast to the highest level type. This means that if an array input has mixed int and float elements, all the integers will be cast to their floating-point equivalents. If an array is mixed with int, float, and string elements, everything is cast to strings.

In [15]:
# Copy
import numpy as np
a = np.array([1,2,3,4])
b = np.array([11,12,13,14])
c = a
print(repr(a))
c[0] = 100
print(repr(a))

d = b.copy()
d[0] = 200
print(repr(b))

array([1, 2, 3, 4])
array([100,   2,   3,   4])
array([200,  12,  13,  14])


In the code example below, c is a reference to a while d is a copy. Therefore, changing c leads to the same change in a, while changing d does not change the value of b.